#!/bin/bash
cd
sudo npm uninstall -g symbol-bootstrap
sudo npm uninstall -g @nemneshia/symbol-bootstrap
rm -rf nemneshia && mkdir nemneshia && cd nemneshia
git clone https://github.com/nemneshia/symbol-bootstrap.git
cd symbol-bootstrap
npm ci
npm run build
sudo npm install -g .
symbol-bootstrap --version
