#!/bin/bash
rm -rf nodebak && mkdir nodebak
cp -r keys nodebak/
cp -r shoestring nodebak/
cp -r rest-cache nodebak/
cp -r startup nodebak/
cp -r docker-compose.yaml nodebak/
cp -r docker-compose-recovery.yaml nodebak/
cp -r logs nodebak/
cp -r seed nodebak/
cp -r userconfig nodebak/
cp -r mongo nodebak/
cp -r linking_transaction.dat nodebak/
cp -r ca.key.pem nodebak/
cp -r renew_voting_keys_transaction.dat nodebak/
sudo chown -R 1000 https-proxy && cp -r https-proxy nodebak/
#
#upgradeで失敗した時は以下の命令を実行
#sudo cp -r nodebak/* . && sudo chown -R 1000 .
#
